# Generated by Django 5.2.15 on 2026-06-11 06:25

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('truckstop_name', models.CharField(help_text='Name of the truck stop or fuel station', max_length=255, verbose_name='Truck Stop Name')),
                ('address', models.CharField(help_text='Full street address of the truck stop', max_length=500, verbose_name='Address')),
                ('city', models.CharField(help_text='City where truck stop is located', max_length=100, verbose_name='City')),
                ('state', models.CharField(help_text='State abbreviation (e.g. TX, CA)', max_length=10, verbose_name='State')),
                ('rack_id', models.IntegerField(help_text='Fuel rack identifier for pricing source', verbose_name='Rack ID')),
                ('retail_price', models.DecimalField(decimal_places=4, help_text='Current retail fuel price', max_digits=10, verbose_name='Retail Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp', verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Truck Stop',
                'verbose_name_plural': 'Truck Stops',
                'constraints': [models.UniqueConstraint(fields=('truckstop_name', 'address', 'city', 'state', 'rack_id', 'retail_price'), name='unique_truckstop_full_record')],
            },
        ),
    ]
