# Generated by Django 5.2.15 on 2026-06-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckstop',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Geographic latitude coordinate', null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='truckstop',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Geographic longitude coordinate', null=True, verbose_name='Longitude'),
        ),
        migrations.AddIndex(
            model_name='truckstop',
            index=models.Index(fields=['latitude', 'longitude'], name='idx_truck_stop_coords'),
        ),
        migrations.AddIndex(
            model_name='truckstop',
            index=models.Index(fields=['retail_price'], name='idx_truck_stop_price'),
        ),
        migrations.AddIndex(
            model_name='truckstop',
            index=models.Index(fields=['state', 'city'], name='idx_truck_stop_location'),
        ),
    ]
